#!/bin/bash

strings=(
  "Classify the following sentence into a category: Hannah: Hey, do you have Betty's number?\nAmanda: Lemme check\nHannah: <file_gif>\nAmanda: Sorry, can't find it.\nAmanda: Ask Larry\nAmanda: He called her last time we were at the park together\nHannah: I don't know him well\nHannah: <file_gif>\nAmanda: Don't be shy, he's very nice\nHannah: If you say so..\nHannah: I'd rather you texted him\nAmanda: Just text him 🙂\nHannah: Urgh.. Alright\nHannah: Bye\nAmanda: Bye bye"
  "Classify the following sentence into a category: Deirdre: Hi Beth, how are you love?\r\nBeth: Hi Auntie Deirdre, I'm been meaning to message you, had a favour to ask.\r\nDeirdre: Wondered if you had any thought about your Mum's 40th, we've got to do something special!\r\nBeth: How about a girls weekend, just mum, me, you and the girls, Kira will have to come back from Uni, of course.\r\nDeirdre: Sounds fab! Get your thinking cap on, it's only in 6 weeks! Bet she's dreading it, I remember doing that!\r\nBeth: Oh yeah, we had a surprise party for you, you nearly had a heart attack! \r\nDeirdre: Well, it was a lovely surprise! Gosh, thats nearly 4 years ago now, time flies! What was the favour, darling?\r\nBeth: Oh, it was just that I fancied trying a bit of work experience in the salon, auntie.\r\nDeirdre: Well, I am looking for Saturday girls, are you sure about it? you could do well in the exams and go on to college or 6th form.\r\nBeth: I know, but it's not for me, auntie, I am doing all foundation papers and I'm struggling with those.\r\nDeirdre: What about a tutor? Kira could help you in the hols.\r\nBeth: Maybe, but I'd like to try working. I'm 16 soon, I'm old enough.\r\nDeirdre: I know. Look, pop in tomorrow after school and we'll have a cuppa and a chat.\r\nBeth: Yes, thanks auntie. I'd really like to try the beauty therapy side.\r\nDeirdre: Its not for the squeamish, mind. Massage, pedicures, not to mention waxing!\r\nBeth: Oh yes, I was chatting to a friend about it yesterday!\r\nDeirdre: Maxine manages the beauty side, you can meet her tomorrow and we'll see how it goes.\r\nBeth: Yes, I'd really like that. \r\nDeirdre: We can try a few hours on a Saturday for a couple of weeks as work experience. I'll give you a tenner or so per session to start off for your lunch, coffee and bus fare etc. If you like, we'll take it from there.\r\nBeth: OK, I like the sound of it! See you tomorrow Auntie! Love you!\r\nDeirdre: Bye, lovely girl! Xx. The answer is: "
  "Classify the following sentence into a category: Sebastian: It's been already a year since we moved here.\r\nSebastian: This is totally the best time of my life.\r\nKevin: Really? \r\nSebastian: Yeah! Totally maaan.\r\nSebastian: During this 1 year I learned more than ever. \r\nSebastian: I learned how to be resourceful, I'm learning responsibility, and I literally have the power to make my dreams come true.\r\nKevin: It's great to hear that.\r\nKevin: It's great that you are satisfied with your decisions.\r\nKevin: And above all it's great to see that you have someone you love by your side :)\r\nSebastian: Exactly!\r\nSebastian: That's another part of my life that is going great.\r\nKevin: I wish I had such a person by my side.\r\nSebastian: Don't worry about it.\r\nSebastian: I have a feeling this day will come shortly.\r\nKevin: Haha. I don' think so, but thanks.\r\nSebastian: This one year proved to me that when you want something really badly, you can achieve it.\r\nKevin: I want to win lottery and I never did :D\r\nSebastian: If you devoted your life to analyze all of the winning numbers, and with your math skills you could win.\r\nKevin: Devote myself and million dollars for lottery tickets.\r\nSebastian: Something like that xD\r\nKevin: I'm happy for you man.\r\nKevin: I really am\r\nSebastian: Thanks. It means a lot my friend :) The answer is: "
  "Classify the following sentence into a category: Salma: <file_video>\r\nSalma: the latest cat meme\r\nHugh: oh sweet, I can never get enough of those lol\r\nHugh: <file_photo>\r\nSalma: hahaha same. The answer is: "
  "Classify the following sentence into a category: Ryan: I have a bad feeling about this\r\nRyan: <file_other>\r\nSebastian: Ukraine...\r\nSebastian: This russian circus will never end...\r\nRyan: I hope the leaders of of nations will react somehow to this shit.\r\nSebastian: I hope so too :( The answer is: "
  "Classify the following sentence into a category: Chris: Hi there! Where are you? Any chance of skyping?\r\nRick: Hi! Our last two days in Cancun before flying to Havana. Yeah, skyping is an idea. When would it suit you?\r\nRick: We don't have the best of connections in the room but I can get you pretty well in the lobby.\r\nChris: What's the time in your place now?\r\nRick: 6:45 pm\r\nChris: It's a quarter to one in the morning here. Am still in front of the box.\r\nRick: Gracious me! Sorry mate. You needn't have answered.\r\nChris: 8-D\r\nRick: Just tell me when we could skype.\r\nChris: Preferably in the evening. Just a few hours earlier than now. And not tomorrow.\r\nRick: Shute! Only tomorrow makes sense as there's no workable internet in Cuba.\r\nChris: Could you make it like 3 pm your time?\r\nRick: Sure.\r\nChris: Perfect. So talk to you tomorrow.\r\nChris: Give my love to Helen please.\r\nRick: I will. Thx. The answer is: "
  "Classify the following sentence into a category: John: wanna go see "A Star is Born" on Wed?\r\nJoan: sorry can\'t\r\nJoan: super busy \r\nJoan: don\'t have time for anything :( \r\nJohn: that\'s a shame\r\nJoan: I\'m free on Thursday\r\nJohn: I could do Thursday\r\nJoan: ok! so around 8pm?\r\nJohn: sure sounds great\r\nJohn: I\'ll see where it\'s palying and send you the details\r\nJoan: ok great! The answer is: "
  "Classify the following sentence into a category: Rob: Are we meeting up 2morrow?\r\nEve: How about Sunday\r\nEve: stores are open so we can go then\r\nRob: Ok I just don't know what time they close\r\nEve: we have ot go in the moring \r\nEve: I have some stuff to do around 3\r\nRob: ok. The answer is: "
  "Classify the following sentence into a category: Lisa: Hello Peter. What have you been doing off late?\r\nPeter: Bit busy with work.\r\nLisa: Too much of work, huh?\r\nPeter: Not really, I’ve been working out\r\nLisa:  Ohh, trying to get in shape?\r\nPeter: Nah, I don’t have much of weight to lose, just want to improve my health.\r\nLisa:  That’s a good thought. I was also thinking of working out a bit. What do you do? Do you go to a Gym?\r\nPeter: Yes, I hold a membership with the one near our office.\r\nLisa: Which exercises do you do regularly?\r\nPeter: I do weights and run on the treadmill.\r\nLisa:  Besides exercises, I think I need to eat better to help me keep in shape.\r\nPeter: Another major requirement for good health is sleep. On an average one requires at least 7-8 hours of sleep.\r\nLisa:  There are a lot of things we can do to stay healthy.\r\nPeter: Yes. One needs to maintain a regime to stay healthy for a long term. The answer is: "
  "Classify the following sentence into a category: Debbie: Help, I don't know which dress to buy! <file_photo> or <file_photo>?\r\nKelly: The red one! It's beautiful.\r\nDenise: It is, but the green one will suit you better.\r\nKelly: Why? Debbie looks good in red.\r\nDenise: She does, but in my opinion that dress would look better on someone taller. Deb needs a shorter one.\r\nKelly: Right, I haven't thought about it.\r\nDebbie: So the green one?\r\nDenise: Definitely!\r\nKelly: Yeah. But can you send me the link to the store? I'm considering buying the red one for myself :D\r\nDebbie: LOL, okay. Here's the link: <file_other>. The answer is: "
)

random_string=${strings[$RANDOM % ${#strings[@]}]}

echo "{\"inputs\":\"$random_string\"}" > "$1"

./vegeta attack -duration=1s -rate=$2/1s -targets=target.list | ./vegeta report --type=text >> $3