#!/bin/bash

strings=(
  "Advancements in artificial intelligence and natural language processing have revolutionized the field of summarization, enabling automated extraction of key information from vast volumes of text data. This has significantly reduced the time required for humans to process and analyze large amounts of textual content, leading to improved productivity and decision-making. NLP models like BERT and GPT-3 have played a pivotal role in achieving state-of-the-art results in text summarization tasks."
  "Climate change is a pressing global issue that demands urgent action. Rising temperatures, extreme weather events, and melting ice caps all signal the need for sustainable solutions to mitigate the impact on our planet. Addressing climate change requires collective efforts from governments, industries, and individuals to adopt eco-friendly practices and transition to renewable energy sources. Awareness campaigns and international agreements are vital to create a unified response to this critical challenge."
  "As technology continues to evolve, the potential applications of artificial intelligence seem limitless. From autonomous vehicles to medical diagnosis, AI is poised to reshape various industries and improve the quality of life. Embracing AI can lead to advancements in healthcare, transportation, and entertainment, creating a more connected and efficient world. However, ethical considerations and responsible AI practices must be prioritized to address potential risks and biases associated with AI algorithms."
  "The Fourth Industrial Revolution, characterized by the fusion of digital, physical, and biological technologies, has ushered in a new era of innovation and disruption, leading to unprecedented opportunities and challenges. Industries need to adapt to rapid changes in technology and skill requirements to stay competitive in this dynamic landscape. Collaboration and continuous learning are crucial for individuals and organizations to thrive in the age of industry 4.0."
  "The exploration of outer space has captivated human imagination for centuries. With recent advancements in space exploration technology, humanity stands on the cusp of interplanetary travel and potential colonization of other celestial bodies. Space missions and telescopic observations continue to reveal the mysteries of the universe and its potential for supporting life. Investments in space research and collaboration between space agencies play a pivotal role in expanding our knowledge of the cosmos."
  "The field of biotechnology holds tremendous promise for addressing global challenges such as disease eradication, sustainable agriculture, and renewable energy production, opening doors to a future shaped by genetic engineering and precision medicine. Biotechnological breakthroughs have already led to life-saving therapies and increased crop yields, paving the way for a more resilient and healthier world. Ethical considerations in biotechnology research are vital to ensure responsible use and prevent potential misuse of genetic technologies."
  "With the rise of e-commerce and online marketplaces, traditional retail paradigms are undergoing a profound transformation. Consumers now enjoy a vast array of choices, seamless transactions, and personalized shopping experiences. Retailers must embrace digitalization and omnichannel strategies to stay relevant in the competitive online market. Last-mile delivery innovations and supply chain optimization are essential for meeting customer expectations in the fast-paced e-commerce landscape."
  "Data privacy and cybersecurity have become paramount concerns in the digital age. The ever-increasing volume of sensitive information demands robust security measures and stringent regulations to safeguard individuals and organizations from cyber threats. Organizations must adopt a proactive approach to cybersecurity and educate users about best practices to protect against data breaches and cyber-attacks. Collaboration between the public and private sectors is critical for sharing threat intelligence and combating cybercrime effectively."
  "The Internet of Things (IoT) has connected billions of devices worldwide, forming a vast network of interconnected smart devices that can gather, process, and exchange data autonomously, paving the way for smart homes, smart cities, and a more interconnected world. IoT applications extend beyond consumer devices, encompassing industrial automation, healthcare monitoring, and environmental sensing, among others. However, securing IoT devices against potential vulnerabilities is essential to prevent unauthorized access and protect user privacy."
  "In the realm of renewable energy, solar power stands out as a promising alternative to fossil fuels. As solar technology becomes more efficient and affordable, solar energy adoption accelerates, playing a crucial role in transitioning to a sustainable energy future. Solar panels, solar farms, and solar-powered devices are now widely used to harness the sun's energy and reduce greenhouse gas emissions. Investments in research and development of solar energy technologies are instrumental in further advancing the adoption of solar power worldwide."
)

random_string=${strings[$RANDOM % ${#strings[@]}]}

echo "{\"prompt\":\"$random_string\", \"task\":\"$1\"}" > "$2"

vegeta attack -duration=1s -rate=$3/1s -targets=target_summ.list | vegeta report --type=text >> $4